version: '3.2'

services:
  db:
    image: timescale/timescaledb:latest-pg12
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: discord
      POSTGRES_USER: discord
      POSTGRES_DB: discord
    ports:
      - "5432:5432"
    networks:
      - azolyzer-tier
    volumes:
      - db-data:/var/lib/postgresql/data/
  redis:
    image: redis
    restart: unless-stopped
    environment:
      PASSWORD: securePassword
    ports:
      - "6379:6379"
    networks:
      - azolyzer-tier
    
  # Monitoring / Logging with Elastic Stack

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    restart: unless-stopped
    environment: 
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: securePassword
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    volumes:
      - type: bind
        source: ./elk/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: es-data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - azolyzer-tier

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.1
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./elk/logstash/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./elk/logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - azolyzer-tier
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./elk/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    environment: 
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - azolyzer-tier
    depends_on:
      - elasticsearch
    
  apm:
    image: docker.elastic.co/apm/apm-server:7.9.1
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./elk/apm.yml
        target: /usr/share/apm-server/apm.yml
        read_only: true
    environment: 
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - azolyzer-tier
    depends_on:
      - elasticsearch

volumes:
  db-data:
  es-data:
networks:
  azolyzer-tier:
    driver: bridge