version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: discord
      POSTGRES_USER: discord
      POSTGRES_DB: discord
    ports:
      - 5432:5432
    networks:
      - discordbot-tier
    volumes:
      - db-data:/var/lib/postgresql/data/
  redis:
    image: redis
    restart: unless-stopped
    environment:
      PASSWORD: securePassword
    ports:
      - 6379:6379
    networks:
      - discordbot-tier
volumes:
  db-data:
networks:
  discordbot-tier:
    driver: bridge