# This workflow will do a clean install of node dependencies and unit test the backend application.

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting up Node js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 14.x
    - name: Installing Dependencies
      run: |
        npm ci
    - name: Backend Testing
      run: |
        npm run test
