# This workflow will do a clean install of node dependencies and unit test the backend application.

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths-ignore: 
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - 'README.md'
      - 'LICENSE'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting up Node js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 14.x
    - name: Installing Dependencies
      working-directory: ./backend
      run: |
        npm ci
    - name: Backend Jest Testing
      working-directory: ./backend
      run: |
        npm run test
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Node js
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 14.x
    - name: Installing Dependencies
      working-directory: ./angular-frontend
      run: |
        npm ci
    - name: Angular Karma Testing
      working-directory: ./angular-frontend
      run: |
        npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    - name: E2E Testing
      working-directory: ./angular-frontend
      run: |
        npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
